language: php
services: mongodb
before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --dev --no-interaction
  - touch src/Graviton/I18nBundle/Resources/translations/i18n.de.odm
  - wget https://scrutinizer-ci.com/ocular.phar
php:
  - 5.5
  - 5.4
script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - composer check
